services:
  bot:
    build: .
    container_name: telegram_bot
    command: python main.py
    env_file:
      - .env   # contains TELEGRAM_TOKEN and DB_* vars
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
    name: telegram_bot_db_data